/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ranger_xyg_xygapp_demos_jni_NdkJniUtils */

#ifndef _Included_com_ranger_xyg_xygapp_demos_jni_NdkJniUtils
#define _Included_com_ranger_xyg_xygapp_demos_jni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ranger_xyg_xygapp_demos_jni_NdkJniUtils
 * Method:    getSampleName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ranger_xyg_xygapp_demos_jni_NdkJniUtils_getSampleName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
